call plug#begin('~/.vim/plugged')

Plug 'phanviet/vim-monokai-pro'

call plug#end()

filetype plugin indent on

let mapleader=","
inoremap jk <esc>
inoremap kj <esc>

set termguicolors
colorscheme monokai_pro

syntax enable

set tabstop=2
set softtabstop=2
set expandtab

autocmd FileType json,yaml setlocal shiftwidth=2 softtabstop=2 expandtab
autocmd FileType ruby setlocal shiftwidth=2 softtabstop=2 expandtab
autocmd FileType javascript,typescript setlocal shiftwidth=2 softtabstop=2 expandtab
autocmd FileType python setlocal shiftwidth=4 softtabstop=4 expandtab
autocmd FileType make setlocal shiftwidth=4 softtabstop=0 noexpandtab

set number relativenumber
set showcmd
set cursorline
filetype indent on
set lazyredraw
set showmatch

set wildmenu
set wildignore+=*/node_modules/*
set grepprg=grep\ -IrsnH
set path+=**
set incsearch
set hlsearch
nnoremap <leader><space> :nohlsearch<CR>

set foldenable
set foldlevelstart=10
set foldnestmax=10
set foldmethod=indent
nnoremap <space> za
let b:match_words = '\s*#\s*region.*$:\s*#\s*endregion'

nnoremap j gj
nnoremap k gk

map <Enter> o<ESC>
map <S-Enter> O<ESC>
